{% set name = "bursty-dynamics" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bursty_dynamics-{{ version }}.tar.gz
  sha256: d95c21fb7b1c18957960f0cdb8ab15547dc652fa8130bd821a38ccd298d1bf3b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - seaborn
    - matplotlib-base
    - scipy

test:
  imports:
    - bursty_dynamics
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/ai-multiply/bursty_dynamics
  summary: bursty_dynamics is a Python package designed to facilitate the analysis of temporal patterns in longitudinal data. It provides functions to calculate the burstiness parameter (BP) and memory coefficient (MC), detect event trains, and visualise results.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mediocretech
