{% set name = "bursty-dynamics" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bursty_dynamics-{{ version }}.tar.gz
  sha256: bed9391ef5a5b057972f61bae38055bd2ea23e98d299d34a4ff406af5edd58e0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - seaborn
    - matplotlib-base
    - scipy

test:
  imports:
    - bursty_dynamics
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/ai-multiply/bursty_dynamics
  summary: bursty_dynamics is a Python package designed to facilitate the analysis of temporal patterns in longitudinal data. It provides functions to calculate the burstiness parameter (BP) and memory coefficient (MC), detect event trains, and visualise results.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mediocretech
